site_name: DocumenterMarkdown.jl
site_description: Markdown / MkDocs backend for Documenter.jl
repo_url: https://github.com/JuliaDocs/DocumenterMarkdown.jl

theme:
  name: material

docs_dir: build

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
